# Generated by Django 4.2.1 on 2023-05-29 08:52

from django.db import migrations, models
import petstagram.photos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_photo_tagged_pets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/pet_photos/', validators=[petstagram.photos.validators.file_size_validator]),
        ),
    ]
