# Generated by Django 4.2.2 on 2023-06-13 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1, 'Value must be greater than 0.1'), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
