# Generated by Django 4.2.2 on 2023-06-06 13:36

from django.db import migrations, models
import expenses_tracker.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', validators=[expenses_tracker.core.validators.file_size_validator]),
        ),
    ]
