# Generated by Django 4.2.2 on 2023-06-12 10:45

import django.core.validators
from django.db import migrations, models
import my_plant_app.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_type', models.CharField(choices=[('Outdoor Plants', 'Outdoor Plants'), ('Indoor Plants', 'Indoor Plants')], max_length=14)),
                ('plant_name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), my_plant_app.core.validators.plant_name_validator])),
                ('plant_image_url', models.URLField()),
                ('plant_description', models.TextField()),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(2)])),
                ('first_name', models.CharField(max_length=20, validators=[my_plant_app.core.validators.validate_first_and_last__name])),
                ('flast_name', models.CharField(max_length=20, validators=[my_plant_app.core.validators.validate_first_and_last__name])),
                ('profile_image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
