# Generated by Django 4.2.1 on 2023-06-03 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_users_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
