# Generated by Django 4.2.1 on 2023-05-31 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-publication_date_time'], 'verbose_name_plural': 'Comments'},
        ),
    ]
