# Generated by Django 4.2.1 on 2023-06-05 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='aget',
            new_name='age',
        ),
    ]
