# Generated by Django 4.2.1 on 2023-05-29 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_pet_options_alter_pet_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ('date_of_birth', 'name')},
        ),
    ]
